system:
  environment: "development"
router:
  port: 3887
  mode: "debug"
nats:
  connectionString: "nats://localhost:4222"
  jwt: "asdf"
  seed: "asdf"
cluster:
  namespace: "default"
  certManagerIssuer: "letsencrypt-prod"
  serviceName: "your-service"
  servicePort: 3000
