apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanityDomainManager
    version: v0.1.0
  name: vanityDomainManager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanityDomainManager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vanityDomainManager
        version: v0.1.0
      name: vanityDomainManager
    spec:
      volumes:
        - name: config
          configMap:
            name: vanityDomainManager-config
      containers:
        - image: geekgonecrazy/vanityDomainManager:v0.1.0
          imagePullPolicy: IfNotPresent
          name: vanityDomainManager
          ports:
            - containerPort: 9595
              protocol: TCP
          volumeMounts:
            - mountPath: "/data/config"
              name: "config"
          command:
            - /root/vanityDomainManager
          args:
            - --configFile=/data/config/config.yaml
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9595
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 9595
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: vanityDomainManager
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 9595
      port: 9595
  selector:
    app: vanityDomainManager
